# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: VINA TRAVEL 
email: thereseloan@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
&nbsp;&nbsp;&nbsp;414 Clement St # 5, San Francisco, CA 94118





# Build settings
markdown: kramdown
permalink : pretty

gems:
  - jekyll-gist
