# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Khang Tran
email: percytran96@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Repository of my projects.
url: "percytran96.github.io" # the base hostname & protocol for your site

github_username:  percytran96

# Build settings
markdown: kramdown
permalink : pretty

gems:
  - jekyll-gist
