# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: VINA TRAVEL 
email: thereseloan@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
 414 Clement St # 5, San Francisco, CA 94118
url: "https://www.google.com/maps/place/Vina+Travel/@37.7832066,-122.4639217,15z/data=!4m2!3m1!1s0x0:0x225448a3418f01a1?sa=X&ved=0ahUKEwjEu7r6wvvVAhXijFQKHeeiBOUQ_BIIazAK" # the base hostname & protocol for your site
  github_username:  Map




# Build settings
markdown: kramdown
permalink : pretty

gems:
  - jekyll-gist
